model: "hosted_vllm/AI-MO/Kimina-Autoformalizer-7B"
temperature: 0.7
top_p: 0.95
nb_samples: 50
max_total_tokens: 4096
max_generated_tokens: 512
use_chat_prompt: true
stopwords:
  - "```\n"
  - ":= by"
  - "sorry"
n_processes: 15
prompt_context: "ZERO_SHOT_KIMINA"
api_key: abc-123
api_base_url: http://localhost:8000/v1
